title: ahimsacode.com
author: ahimsacode
description: > # this means to ignore newlines until "baseurl:"
  This is just a little blog where I share my thoughts and ideas along with my progress learning and transforming into an IT professional.

# social links
twitter_username: ahimsatravis # DO NOT include the @ character, or else the build will fail!
github_username:  ahimsacode # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-hacker
