title: ahimsacode developer learning blog
author: ahimsacode
email: github-blog@ahimsa.33mail.com
description: > # this means to ignore newlines until "baseurl:"
I'm glad you are here. I plan to use this space to blog about my experiences (re)learning to be a developer. It may also just end up being an abandoned project used just as a learning experience. We'll see...

# social links
twitter_username: sacredtrouble # DO NOT include the @ character, or else the build will fail!
github_username:  ahimsacode # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
